#Set costmap to a rolling window mode
local_costmap:
    publish_voxel_map: false
    global_frame: odom
    robot_base_frame: base_footprint
    update_frequency: 10.0
    publish_frequency: 1.0
    static_map: false
    rolling_window: true
    width: 20.0
    height: 20.0
    resolution: 0.1
    origin_x: 0.0
    origin_y: 0.0
